# Generated by Django 4.2.2 on 2024-08-14 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='avatars',
            new_name='avatar',
        ),
    ]
