# Generated by Django 4.2.2 on 2024-08-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Загрузите аватар', null=True, upload_to='users/avatars/', verbose_name='Аватар'),
        ),
    ]
