# Generated by Django 4.2.2 on 2024-08-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_alter_blog_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('can_title', 'Можно менять заголовок'), ('can_content', 'Можно менять описание'), ('can_preview_image', 'Можно менять изображение к блогу'), ('can_is_published', 'Можно отменять публикацию')], 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
    ]
