# Generated by Django 4.2.2 on 2024-08-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'category', 'price'], 'permissions': [('can_is_published_product', 'Можно отменить публикацию продукта'), ('can_description_product', 'Можно менять описание любого продукта'), ('can_category_product', 'Можно изменить категорию продукта')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
    ]
